/**
 * GENERATED by scripts/vendor-fonts.mjs — do not edit by hand.
 *
 * Self-hosted @font-face rules for the studio theme. Serving these from our own
 * origin removes the render-blocking third-party stylesheet that docs/SEO.md §4
 * recorded as debt, and it is also the only way any environment without access
 * to fonts.googleapis.com renders the real typefaces rather than the fallback
 * stack.
 *
 * latin + latin-ext only. latin-ext carries č/š/ž and is therefore mandatory
 * for these shops; the subsets we drop are weight nobody here would download.
 *
 * 6 faces, 128 KB total.
 */
export const STUDIO_FONT_FACE_CSS = `
@font-face{font-family:'Chivo';font-style:normal;font-weight:500;font-display:swap;src:url('/fonts/chivo-500-latin-ext.woff2') format('woff2');unicode-range:U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF}
@font-face{font-family:'Chivo';font-style:normal;font-weight:500;font-display:swap;src:url('/fonts/chivo-500-latin.woff2') format('woff2');unicode-range:U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD}
@font-face{font-family:'DM Sans';font-style:normal;font-weight:400 500;font-display:swap;src:url('/fonts/dm-sans-400-500-latin-ext.woff2') format('woff2');unicode-range:U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF}
@font-face{font-family:'DM Sans';font-style:normal;font-weight:400 500;font-display:swap;src:url('/fonts/dm-sans-400-500-latin.woff2') format('woff2');unicode-range:U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD}
@font-face{font-family:'Plus Jakarta Sans';font-style:normal;font-weight:200 800;font-display:swap;src:url('/fonts/plus-jakarta-sans-200-800-latin-ext.woff2') format('woff2');unicode-range:U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF}
@font-face{font-family:'Plus Jakarta Sans';font-style:normal;font-weight:200 800;font-display:swap;src:url('/fonts/plus-jakarta-sans-200-800-latin.woff2') format('woff2');unicode-range:U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD}
`;

/**
 * The display and body faces' files, preloaded by render/page.ts.
 *
 * The display face sets the h1, which is the LCP text element on every
 * landing page. The body face sets the prose — and it is preloaded because
 * NOT preloading it was measured, by scripts/audit-site.mjs, as CLS 0.1451 on
 * /blog at mobile width and 0.0879 on /trgovina at desktop: the fallback's
 * metrics lay out the nav, the intro and the lists, and every one of them
 * moves when the real face arrives. With both preloaded that audit reports no
 * layout shift anywhere.
 *
 * The label face is not preloaded: it sets eyebrows and meta lines, which do
 * not reflow a column of prose when they swap.
 */
export const STUDIO_PRELOAD: readonly string[] = ["/fonts/chivo-500-latin-ext.woff2","/fonts/chivo-500-latin.woff2","/fonts/plus-jakarta-sans-200-800-latin-ext.woff2","/fonts/plus-jakarta-sans-200-800-latin.woff2"];
