/**
 * Imagery the studio theme can paint, and the rules about what it may claim.
 *
 * THESE ARE PLACEHOLDERS, AND THE DISTINCTION MATTERS COMMERCIALLY.
 * The files come from the source theme's own asset bundle, which is a
 * FURNITURE store: sofas, dining chairs, beds, lamps. The shops on this
 * network sell saunas, cold plunge tubs, hot tubs, massage chairs, stone-resin
 * baths and billiard tables. A photograph of a dining chair is therefore fine
 * as atmosphere and fine as scaffolding while a shop is pre-live — and is not
 * fine as the picture of the thing a customer is paying €1,500–15,000 for.
 *
 * So the media splits by what a slot CLAIMS:
 *
 *   motif / scene / room  — atmosphere. A room interior beside a buying guide
 *                           claims nothing about the product, exactly as
 *                           lifestyle photography does on any storefront.
 *   cutout / tile         — PRODUCT SLOTS. These carry the implication "this
 *                           is what you are buying", so the furniture cutouts
 *                           are NOT wired into them. Product slots keep their
 *                           drawn placeholder until the shop's own photography
 *                           exists.
 *
 * `isPlaceholderMedia` backs a launch gate: a shop cannot flip `live: true`
 * while any of this is still on the page. See src/tenants/media.test.ts.
 */

/** Everything under /img is generated by scripts/build-media.mjs. */
const BASE = "/img/";

export interface Media {
  /** Path served by the Worker's static-asset binding. */
  readonly src: string;
  /**
   * Intrinsic size, so every slot can reserve space and CLS stays at zero —
   * the budget in docs/SEO.md §4 is a gate, not an aspiration.
   */
  readonly w: number;
  readonly h: number;
}

const m = (file: string, w: number, h: number): Media => ({ src: BASE + file, w, h });

/**
 * The eye. The source paints it behind the testimonial band and the offer
 * panel as a large, faint motif.
 *
 * This is worth naming precisely because it was read wrong twice: first as an
 * "arrow stadium" (the arrow IS a stadium, but that is the button glyph), then
 * as a drawn concentric ellipse. It is neither — it is a supplied raster, and
 * the shape is an eye. Drawing it in SVG was always going to be an
 * approximation of a thing we had all along.
 */
export const MOTIF_EYE = m("motif-01.webp", 900, 1273);

/** Wide banner scenes — 1.92:1. Full-bleed bands. */
export const SCENES: readonly Media[] = [
  m("scene-01.webp", 1920, 1000),
  m("scene-02.webp", 1920, 1000),
  m("scene-03.webp", 1920, 1000),
  m("scene-04.webp", 1920, 1000),
];

/**
 * Room interiors, ~4:3. Editorial and guide cards.
 *
 * Only the four full-size exports are listed. The build also produced small
 * crops (364x300, 544x448) that the shape sort filed here — those are icon
 * scale, and a 364px file stretched across a guide card is worse than the
 * drawn placeholder it would replace.
 */
export const ROOMS: readonly Media[] = [
  m("room-01.webp", 1600, 1199),
  m("room-02.webp", 1600, 1174),
  m("room-03.webp", 1600, 1023),
  m("room-06.webp", 1600, 1199),
];

/** Tall crops — testimonial photography. Same filter as ROOMS. */
export const PORTRAITS: readonly Media[] = [
  m("portrait-03.webp", 900, 1414),
  m("portrait-05.webp", 900, 1406),
  m("portrait-08.webp", 726, 922),
];

/**
 * Deterministic pick, so a shop's imagery is stable across renders and two
 * shops on the same theme do not land on the same picture. Not random: a page
 * that reshuffles its photography on every request is a page that looks broken
 * to anyone who reloads.
 */
export function pick<T>(list: readonly T[], seed: string, offset = 0): T {
  let h = 0;
  for (let i = 0; i < seed.length; i++) h = (h * 31 + seed.charCodeAt(i)) >>> 0;
  return list[(h + offset) % list.length] as T;
}

/**
 * True for any media this module can serve. The launch gate uses it: none of
 * this is the shop's own photography, so a live shop showing it is showing a
 * stranger's furniture.
 */
export function isPlaceholderMedia(src: string): boolean {
  return src.startsWith(BASE);
}

/**
 * A picture that decorates rather than informs. Marked aria-hidden and given
 * an empty alt: a screen reader announcing "living room interior" beside a
 * sauna guide would be describing scaffolding as if it were content.
 */
export function decorativeImg(media: Media, cls: string, sizes: string): string {
  return (
    '<img class="' + cls + '" src="' + media.src + '"' +
    ' width="' + media.w + '" height="' + media.h + '"' +
    ' sizes="' + sizes + '"' +
    ' loading="lazy" decoding="async" alt="" aria-hidden="true">'
  );
}
