/**
 * GENERATED by scripts/build-media.mjs — do not edit.
 *
 * Every width actually written under public/img, keyed by the master file
 * media.ts names. decorativeImg turns these into a real srcset.
 *
 * It is generated rather than hand-kept because a srcset that offers a
 * width the build did not write is a 404 the browser picks on purpose, and
 * a `w` descriptor that does not match the file's real width makes every
 * selection after it wrong. Both are silent.
 */

/** [file, intrinsic width] rungs, narrowest first. */
export type Rung = readonly [file: string, width: number];

export const MEDIA_WIDTHS: Readonly<Record<string, readonly Rung[]>> = {
  "cutout-01.webp": [["cutout-01.webp", 214]],
  "cutout-02.webp": [["cutout-02-450.webp", 450], ["cutout-02.webp", 900]],
  "cutout-03.webp": [["cutout-03.webp", 237]],
  "cutout-04.webp": [["cutout-04.webp", 407]],
  "cutout-05.webp": [["cutout-05-450.webp", 450], ["cutout-05.webp", 711]],
  "cutout-06.webp": [["cutout-06.webp", 387]],
  "cutout-07.webp": [["cutout-07.webp", 256]],
  "cutout-08.webp": [["cutout-08-450.webp", 450], ["cutout-08.webp", 788]],
  "cutout-09.webp": [["cutout-09.webp", 387]],
  "cutout-10.webp": [["cutout-10.webp", 238]],
  "cutout-11.webp": [["cutout-11-450.webp", 450], ["cutout-11.webp", 900]],
  "cutout-12.webp": [["cutout-12-450.webp", 450], ["cutout-12.webp", 838]],
  "cutout-13.webp": [["cutout-13-450.webp", 450], ["cutout-13.webp", 900]],
  "cutout-14.webp": [["cutout-14-450.webp", 450], ["cutout-14.webp", 510]],
  "motif-01.webp": [["motif-01-600.webp", 600], ["motif-01.webp", 900]],
  "portrait-01.webp": [["portrait-01.webp", 342]],
  "portrait-02.webp": [["portrait-02.webp", 342]],
  "portrait-03.webp": [["portrait-03-400.webp", 400], ["portrait-03-640.webp", 640], ["portrait-03.webp", 900]],
  "portrait-04.webp": [["portrait-04-400.webp", 400], ["portrait-04.webp", 464]],
  "portrait-05.webp": [["portrait-05-400.webp", 400], ["portrait-05-640.webp", 640], ["portrait-05.webp", 900]],
  "portrait-06.webp": [["portrait-06.webp", 342]],
  "portrait-07.webp": [["portrait-07.webp", 342]],
  "portrait-08.webp": [["portrait-08-400.webp", 400], ["portrait-08-640.webp", 640], ["portrait-08.webp", 726]],
  "room-01.webp": [["room-01-480.webp", 480], ["room-01-800.webp", 800], ["room-01-1200.webp", 1200], ["room-01.webp", 1600]],
  "room-02.webp": [["room-02-480.webp", 480], ["room-02-800.webp", 800], ["room-02-1200.webp", 1200], ["room-02.webp", 1600]],
  "room-03.webp": [["room-03-480.webp", 480], ["room-03-800.webp", 800], ["room-03-1200.webp", 1200], ["room-03.webp", 1600]],
  "room-04.webp": [["room-04.webp", 364]],
  "room-05.webp": [["room-05-480.webp", 480], ["room-05.webp", 544]],
  "room-06.webp": [["room-06-480.webp", 480], ["room-06-800.webp", 800], ["room-06-1200.webp", 1200], ["room-06.webp", 1600]],
  "scene-01.webp": [["scene-01-640.webp", 640], ["scene-01-960.webp", 960], ["scene-01-1280.webp", 1280], ["scene-01-1600.webp", 1600], ["scene-01.webp", 1920]],
  "scene-02.webp": [["scene-02-640.webp", 640], ["scene-02-960.webp", 960], ["scene-02-1280.webp", 1280], ["scene-02-1600.webp", 1600], ["scene-02.webp", 1920]],
  "scene-03.webp": [["scene-03-640.webp", 640], ["scene-03-960.webp", 960], ["scene-03-1280.webp", 1280], ["scene-03-1600.webp", 1600], ["scene-03.webp", 1920]],
  "scene-04.webp": [["scene-04-640.webp", 640], ["scene-04-960.webp", 960], ["scene-04-1280.webp", 1280], ["scene-04-1600.webp", 1600], ["scene-04.webp", 1920]],
  "tile-01.webp": [["tile-01-400.webp", 400], ["tile-01.webp", 546]],
  "tile-02.webp": [["tile-02-400.webp", 400], ["tile-02.webp", 800]],
  "tile-03.webp": [["tile-03-400.webp", 400], ["tile-03.webp", 800]],
  "tile-04.webp": [["tile-04-400.webp", 400], ["tile-04.webp", 800]],
  "tile-05.webp": [["tile-05-400.webp", 400], ["tile-05.webp", 800]],
  "tile-06.webp": [["tile-06-400.webp", 400], ["tile-06.webp", 800]],
  "tile-07.webp": [["tile-07-400.webp", 400], ["tile-07.webp", 800]],
  "tile-08.webp": [["tile-08-400.webp", 400], ["tile-08.webp", 800]],
};
