/**
 * Imagery the studio theme can paint, and the rules about what it may claim.
 *
 * THESE ARE PLACEHOLDERS, AND THE DISTINCTION MATTERS COMMERCIALLY.
 * The files come from the source theme's own asset bundle, which is a
 * FURNITURE store: sofas, dining chairs, beds, lamps. The shops on this
 * network sell saunas, cold plunge tubs, hot tubs, massage chairs, stone-resin
 * baths and billiard tables. A photograph of a dining chair is therefore fine
 * as atmosphere and fine as scaffolding while a shop is pre-live — and is not
 * fine as the picture of the thing a customer is paying €1,500–15,000 for.
 *
 * So the media splits by what a slot CLAIMS:
 *
 *   motif / scene / room  — atmosphere. A room interior beside a buying guide
 *                           claims nothing about the product, exactly as
 *                           lifestyle photography does on any storefront.
 *   cutout / tile         — PRODUCT SLOTS. These carry the implication "this
 *                           is what you are buying", so the furniture cutouts
 *                           are NOT wired into them. Product slots keep their
 *                           drawn placeholder until the shop's own photography
 *                           exists.
 *
 * `isPlaceholderMedia` backs a launch gate: a shop cannot flip `live: true`
 * while any of this is still on the page. See src/tenants/media.test.ts.
 */

import { MEDIA_WIDTHS } from "./media-widths";
import { OWN_HERO } from "./own-hero";
import { OWN_MEDIA } from "./own-media";

/** Everything under /img is generated by scripts/build-media.mjs. */
const BASE = "/img/";

/**
 * THE SHOP'S OWN PHOTOGRAPHY, as opposed to the source theme's bundle.
 *
 * Everything else in this module is borrowed furniture: fine as atmosphere,
 * never as a picture of the goods, and the launch gate below refuses to let a
 * shop go live while any of it is on the page. Files under /img/own/ are the
 * exception — they are pictures of what the shop actually sells, so they do
 * not trip the gate and they do not carry "simbolična fotografija".
 *
 * Putting them in the repo rather than in Supabase is deliberate for the hero
 * specifically: it is the LCP element on the page the whole SEO strategy
 * rests on, and a versioned file served from the edge before the Worker even
 * runs is a shorter path than a proxied object. Model photography belongs in
 * Supabase, through the admin panel, where it can change without a deploy.
 */
const OWN = BASE + "own/";

/**
 * Anything paintable: a repo asset, which always knows its own size, or a
 * Supabase-served photograph, which does not. See the note in own-media.ts —
 * every frame carrying one sets its own aspect-ratio and sizes the image to
 * 100%, so the box is reserved by CSS and an absent width/height costs no
 * layout stability. Inventing the numbers would cost correctness.
 */
export interface Paintable {
  readonly src: string;
  readonly w?: number;
  readonly h?: number;
}

export interface Media {
  /** Path served by the Worker's static-asset binding. */
  readonly src: string;
  /**
   * Intrinsic size, so every slot can reserve space and CLS stays at zero —
   * the budget in docs/SEO.md §4 is a gate, not an aspiration.
   */
  readonly w: number;
  readonly h: number;
}

const m = (file: string, w: number, h: number): Media => ({ src: BASE + file, w, h });

/**
 * THE BORROWED IMAGERY IS GONE, AND WITH IT 3.6 MB AND THE LAUNCH GATE.
 *
 * MOTIF_EYE, SCENES, ROOMS and PORTRAITS used to live here: the source
 * theme's own asset bundle, which is a FURNITURE store — sofas, dining
 * chairs, beds, a sideboard with a vase of flowers on it. They were wired in
 * as atmosphere on the argument that a room interior beside a buying guide
 * claims nothing about the product, and that argument held. What it did not
 * survive was contact with the rendered page: the shop reads as a furniture
 * catalogue that happens to mention hot tubs, and every one of those files is
 * a picture nobody here has the right to publish.
 *
 * So the site now shows the shop's OWN photography or it shows nothing. That
 * is a real constraint on the design rather than a gap in it: sections that
 * were photograph-plus-copy are now copy, and they have to earn their place
 * on type and space, which is what this theme is actually good at.
 *
 * The launch gate goes quiet as a side effect. isPlaceholderMedia() flagged
 * anything under /img/ that was not the shop's own, and src/tenants/
 * media.test.ts failed the build if a shop flipped live:true while any of it
 * was still on the page. Nothing trips it now — not because the rule relaxed
 * but because the imagery it was written to catch no longer exists.
 */

/**
 * Deterministic pick, so a shop's imagery is stable across renders and two
 * shops on the same theme do not land on the same picture. Not random: a page
 * that reshuffles its photography on every request is a page that looks broken
 * to anyone who reloads.
 */
export function pick<T>(list: readonly T[], seed: string, offset = 0): T {
  let h = 0;
  for (let i = 0; i < seed.length; i++) h = (h * 31 + seed.charCodeAt(i)) >>> 0;
  return list[(h + offset) % list.length] as T;
}

/**
 * True for any media this module can serve. The launch gate uses it: none of
 * this is the shop's own photography, so a live shop showing it is showing a
 * stranger's furniture.
 */
export function isPlaceholderMedia(src: string): boolean {
  return src.startsWith(BASE) && !src.startsWith(OWN);
}

/**
 * A shop's own hero photograph, where one exists.
 *
 * Empty until the files are in the repo. Adding one is a single entry here
 * plus the file under public/img/own/ — the hero then uses it instead of a
 * borrowed room, and drops the "simbolična fotografija" line, because the
 * picture is no longer symbolic of anything: it is the product.
 *
 * A photograph may only be listed against the shop that sells what is in it.
 * A hot tub is the bazen shop's; putting it on the sauna shop would be the
 * same error as the furniture, made with better pictures.
 */
export const SHOP_HERO: Readonly<Partial<Record<string, Paintable>>> = OWN_HERO;

/**
 * The width ladder for a master file, as `srcset` syntax, or "" when the build
 * wrote only one width (the cutouts, and any source too small to ladder).
 */
function srcset(src: string): string {
  // The hero plate is the one image left under /img/own/, and it carries its
  // own ladder in a generated module rather than in MEDIA_WIDTHS — a lookup
  // there would find nothing and ship the 2000px master to a phone.
  //
  // Model photography used to be handled here too. It lives in Supabase now
  // and is served from /media/, so it never reaches this branch; a lookup for
  // it here would be dead code that reads like a working path. Those files
  // have no ladder at all until they are re-uploaded through /admin, and
  // OwnPhoto.widths is empty for every one of them — see own-media.ts.
  if (src.startsWith(OWN)) {
    const plate = Object.values(OWN_HERO).find((p) => p?.src === src);
    if (!plate || plate.widths.length < 2) return "";
    return plate.widths.map((r) => r[0] + " " + r[1] + "w").join(", ");
  }
  const rungs = MEDIA_WIDTHS[src.slice(BASE.length)];
  if (!rungs || rungs.length < 2) return "";
  return rungs.map((r) => BASE + r[0] + " " + r[1] + "w").join(", ");
}

/**
 * A picture that decorates rather than informs. Marked aria-hidden and given
 * an empty alt: a screen reader announcing "living room interior" beside a
 * sauna guide would be describing scaffolding as if it were content.
 *
 * `sizes` is only emitted alongside a `srcset`. For a long time it was emitted
 * on its own, which does nothing at all — every slot was handed the 1600px or
 * 1920px master whatever it painted, so a 437px guide card downloaded ~100 KB
 * to show ~13 KB of pixels, eight times down the home page. The attribute
 * looked like responsive images and was inert.
 */
/**
 * A photograph of the product, with a described alt.
 *
 * The opposite of decorativeImg in every way that matters: this one INFORMS.
 * It is not aria-hidden and its alt is not empty, because a picture of the
 * thing being sold is content — for a screen reader and for the image search
 * that is a real channel at this ticket size. The schema enforces the same
 * rule on the database side (product_media.alt is NOT NULL with a length
 * check), so the two agree.
 */
export function productImg(
  photo: { src: string; w?: number; h?: number; widths: readonly (readonly [string, number])[] },
  cls: string,
  sizes: string,
  alt: string,
  eager = false,
): string {
  const set =
    photo.widths.length > 1
      ? photo.widths.map((r) => r[0] + " " + r[1] + "w").join(", ")
      : "";
  return (
    '<img class="' + cls + '" src="' + photo.src + '"' +
    (set ? ' srcset="' + set + '" sizes="' + sizes + '"' : "") +
    (photo.w && photo.h ? ' width="' + photo.w + '" height="' + photo.h + '"' : "") +
    (eager ? ' loading="eager" fetchpriority="high"' : ' loading="lazy"') +
    ' decoding="async" alt="' + alt.replace(/"/g, "&quot;") + '">'
  );
}

export function decorativeImg(media: Paintable, cls: string, sizes: string): string {
  const set = srcset(media.src);
  return (
    '<img class="' + cls + '" src="' + media.src + '"' +
    (set ? ' srcset="' + set + '" sizes="' + sizes + '"' : "") +
    (media.w && media.h ? ' width="' + media.w + '" height="' + media.h + '"' : "") +
    ' loading="lazy" decoding="async" alt="" aria-hidden="true">'
  );
}

/**
 * Every photograph the shop owns, flattened, in a stable order.
 *
 * The decorative slots that used to hold the source theme's rooms and scenes
 * draw from here instead. It is a narrower well — sixteen studio shots rather
 * than a stocked library — so a slot that wants six distinct pictures gets
 * six distinct pictures and no more, and pick() still keeps the choice stable
 * across renders.
 */
export const OWN_PHOTOS: readonly Paintable[] = Object.values(OWN_MEDIA)
  .flat()
  // exactOptionalPropertyTypes is on, so an absent size must be an ABSENT
  // key rather than an explicit undefined — spreading conditionally is the
  // difference between "unmeasured" and "measured as nothing".
  .map((p) => ({ src: p.src, ...(p.w && p.h ? { w: p.w, h: p.h } : {}) }));
