/**
 * GENERATED by scripts/build-own-media.mjs — do not edit.
 *
 * A shop's OWN product photography, keyed by "<shop>/<model-slug>", in the
 * order the gallery shows it. Everything here lives under /img/own/, which
 * is the path isPlaceholderMedia deliberately does not flag: these are
 * pictures of what the shop sells, not the source theme's furniture.
 *
 * The widths are the ones actually written. Generated rather than
 * hand-kept because a srcset offering a width the build did not write is a
 * 404 the browser picks on purpose, and both failures are silent.
 */

export interface OwnPhoto {
  readonly src: string;
  readonly w: number;
  readonly h: number;
  /** [file, intrinsic width] rungs, narrowest first. */
  readonly widths: readonly (readonly [string, number])[];
}

export const OWN_MEDIA: Readonly<Record<string, readonly OwnPhoto[]>> = {
  "bazen/mali-195": [
    {
      src: "/img/own/bazen/mali-195/zr805-1.webp",
      w: 600,
      h: 600,
      widths: [["/img/own/bazen/mali-195/zr805-1-400.webp", 400], ["/img/own/bazen/mali-195/zr805-1.webp", 600]],
    },
    {
      src: "/img/own/bazen/mali-195/zr805-2.webp",
      w: 600,
      h: 600,
      widths: [["/img/own/bazen/mali-195/zr805-2-400.webp", 400], ["/img/own/bazen/mali-195/zr805-2.webp", 600]],
    },
    {
      src: "/img/own/bazen/mali-195/zr805-4.webp",
      w: 600,
      h: 600,
      widths: [["/img/own/bazen/mali-195/zr805-4-400.webp", 400], ["/img/own/bazen/mali-195/zr805-4.webp", 600]],
    },
    {
      src: "/img/own/bazen/mali-195/zr805-5.webp",
      w: 600,
      h: 600,
      widths: [["/img/own/bazen/mali-195/zr805-5-400.webp", 400], ["/img/own/bazen/mali-195/zr805-5.webp", 600]],
    },
    {
      src: "/img/own/bazen/mali-195/zr805-6.webp",
      w: 600,
      h: 600,
      widths: [["/img/own/bazen/mali-195/zr805-6-400.webp", 400], ["/img/own/bazen/mali-195/zr805-6.webp", 600]],
    },
    {
      src: "/img/own/bazen/mali-195/zr805-7.webp",
      w: 600,
      h: 600,
      widths: [["/img/own/bazen/mali-195/zr805-7-400.webp", 400], ["/img/own/bazen/mali-195/zr805-7.webp", 600]],
    },
  ],
  "bazen/veliki-230": [
    {
      src: "/img/own/bazen/veliki-230/zr801-1.webp",
      w: 600,
      h: 600,
      widths: [["/img/own/bazen/veliki-230/zr801-1-400.webp", 400], ["/img/own/bazen/veliki-230/zr801-1.webp", 600]],
    },
    {
      src: "/img/own/bazen/veliki-230/zr801-2.webp",
      w: 600,
      h: 600,
      widths: [["/img/own/bazen/veliki-230/zr801-2-400.webp", 400], ["/img/own/bazen/veliki-230/zr801-2.webp", 600]],
    },
    {
      src: "/img/own/bazen/veliki-230/zr801-3.webp",
      w: 600,
      h: 600,
      widths: [["/img/own/bazen/veliki-230/zr801-3-400.webp", 400], ["/img/own/bazen/veliki-230/zr801-3.webp", 600]],
    },
    {
      src: "/img/own/bazen/veliki-230/zr801-4.webp",
      w: 600,
      h: 600,
      widths: [["/img/own/bazen/veliki-230/zr801-4-400.webp", 400], ["/img/own/bazen/veliki-230/zr801-4.webp", 600]],
    },
    {
      src: "/img/own/bazen/veliki-230/zr801-5.webp",
      w: 600,
      h: 600,
      widths: [["/img/own/bazen/veliki-230/zr801-5-400.webp", 400], ["/img/own/bazen/veliki-230/zr801-5.webp", 600]],
    },
    {
      src: "/img/own/bazen/veliki-230/zr801-6.webp",
      w: 600,
      h: 600,
      widths: [["/img/own/bazen/veliki-230/zr801-6-400.webp", 400], ["/img/own/bazen/veliki-230/zr801-6.webp", 600]],
    },
    {
      src: "/img/own/bazen/veliki-230/zr801-7.webp",
      w: 600,
      h: 600,
      widths: [["/img/own/bazen/veliki-230/zr801-7-400.webp", 400], ["/img/own/bazen/veliki-230/zr801-7.webp", 600]],
    },
    {
      src: "/img/own/bazen/veliki-230/zr801-8.webp",
      w: 600,
      h: 600,
      widths: [["/img/own/bazen/veliki-230/zr801-8-400.webp", 400], ["/img/own/bazen/veliki-230/zr801-8.webp", 600]],
    },
    {
      src: "/img/own/bazen/veliki-230/zr801-9.webp",
      w: 600,
      h: 600,
      widths: [["/img/own/bazen/veliki-230/zr801-9-400.webp", 400], ["/img/own/bazen/veliki-230/zr801-9.webp", 600]],
    },
    {
      src: "/img/own/bazen/veliki-230/zr801-10.webp",
      w: 600,
      h: 600,
      widths: [["/img/own/bazen/veliki-230/zr801-10-400.webp", 400], ["/img/own/bazen/veliki-230/zr801-10.webp", 600]],
    },
  ],
};
