/**
 * GENERATED by scripts/build-hero-plate.mjs — do not edit.
 *
 * A shop's own hero plate: its product photography composed onto a dark
 * ground, at the widths the build actually wrote. Lives under /img/own/,
 * which is the path isPlaceholderMedia does not flag, so the hero showing
 * one drops "simbolična fotografija" and stops blocking the launch gate.
 */

export interface HeroPlate {
  readonly src: string;
  readonly w: number;
  readonly h: number;
  /** [file, intrinsic width] rungs, narrowest first. */
  readonly widths: readonly (readonly [string, number])[];
}

export const OWN_HERO: Readonly<Partial<Record<string, HeroPlate>>> = {
  bazen: {
    src: "/img/own/bazen-hero.webp",
    w: 2000,
    h: 1100,
    widths: [["/img/own/bazen-hero-640.webp", 640], ["/img/own/bazen-hero-960.webp", 960], ["/img/own/bazen-hero-1280.webp", 1280], ["/img/own/bazen-hero-1600.webp", 1600], ["/img/own/bazen-hero.webp", 2000]],
  },
};
