#!/usr/bin/env node
/**
 * Vendor the theme's webfonts into public/fonts and generate the @font-face
 * rules that serve them from our own origin.
 *
 * Two reasons, one of which only became visible once the pages could be
 * screenshotted:
 *
 * 1. PERFORMANCE. A third-party stylesheet on the critical path costs a DNS
 *    lookup, a TLS handshake and a round trip before the first glyph can even
 *    be requested — and it is render-blocking. docs/SEO.md §4 recorded this as
 *    debt against the studio theme. Self-hosting removes the origin entirely.
 *
 * 2. TRUTHFULNESS. Any environment that cannot reach fonts.googleapis.com
 *    renders the fallback stack. That includes this sandbox's browser, which
 *    means every screenshot review was of the wrong typeface.
 *
 * Only the latin and latin-ext subsets are kept. latin-ext is the one that
 * carries č/š/ž, so it is not optional here; every other subset (cyrillic,
 * greek, vietnamese) is weight these shops never need.
 *
 *   node scripts/vendor-fonts.mjs
 */

import fs from "node:fs";
import path from "node:path";

const UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 " +
  "(KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36";

const CSS_URL =
  "https://fonts.googleapis.com/css2?family=Chivo:wght@500" +
  "&family=DM+Sans:opsz,wght@9..40,400..500" +
  "&family=Plus+Jakarta+Sans:wght@400;500;700&display=swap";

const KEEP = new Set(["latin", "latin-ext"]);
const OUT_DIR = path.join(process.cwd(), "public", "fonts");
const CSS_OUT = path.join(process.cwd(), "src", "themes", "studio", "fonts.ts");

const res = await fetch(CSS_URL, { headers: { "user-agent": UA } });
if (!res.ok) {
  console.error("Could not fetch the font stylesheet: HTTP " + res.status);
  process.exit(1);
}
const css = await res.text();

fs.mkdirSync(OUT_DIR, { recursive: true });
for (const f of fs.readdirSync(OUT_DIR)) fs.unlinkSync(path.join(OUT_DIR, f));

// Google emits `/* subset */` immediately before each @font-face it labels.
const blocks = [...css.matchAll(/\/\*\s*([a-z-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g)];
const faces = [];
let bytes = 0;

for (const [, subset, block] of blocks) {
  if (!KEEP.has(subset)) continue;
  const family = (block.match(/font-family:\s*'([^']+)'/) || [])[1];
  const weight = (block.match(/font-weight:\s*([^;]+)/) || [])[1].trim();
  const style = (block.match(/font-style:\s*(\w+)/) || [])[1] || "normal";
  const url = (block.match(/url\(([^)]+)\)/) || [])[1];
  const range = (block.match(/unicode-range:\s*([^;}]+)/) || [])[1].trim();
  if (!family || !url) continue;

  const slug =
    family.toLowerCase().replace(/[^a-z0-9]+/g, "-") + "-" +
    weight.replace(/\s+/g, "-") + "-" + subset + ".woff2";

  const bin = await fetch(url, { headers: { "user-agent": UA } });
  if (!bin.ok) {
    console.error("FAIL " + slug + " HTTP " + bin.status);
    process.exit(1);
  }
  const buf = Buffer.from(await bin.arrayBuffer());
  fs.writeFileSync(path.join(OUT_DIR, slug), buf);
  bytes += buf.length;
  faces.push({ family, weight, style, slug, range, subset });
  console.log("  " + slug.padEnd(42) + (buf.length / 1024).toFixed(1).padStart(6) + " KB");
}

if (!faces.length) {
  console.error("No faces matched the kept subsets — refusing to write an empty sheet.");
  process.exit(1);
}

const rules = faces
  .map(
    (f) =>
      "@font-face{font-family:'" + f.family + "';font-style:" + f.style +
      ";font-weight:" + f.weight +
      // swap, not optional: these shops are text-first, and a headline that
      // never arrives is worse than one that reflows once.
      ";font-display:swap;src:url('/fonts/" + f.slug + "') format('woff2')" +
      ";unicode-range:" + f.range + "}",
  )
  .join("\n");

const header = `/**
 * GENERATED by scripts/vendor-fonts.mjs — do not edit by hand.
 *
 * Self-hosted @font-face rules for the studio theme. Serving these from our own
 * origin removes the render-blocking third-party stylesheet that docs/SEO.md §4
 * recorded as debt, and it is also the only way any environment without access
 * to fonts.googleapis.com renders the real typefaces rather than the fallback
 * stack.
 *
 * latin + latin-ext only. latin-ext carries č/š/ž and is therefore mandatory
 * for these shops; the subsets we drop are weight nobody here would download.
 *
 * ${faces.length} faces, ${(bytes / 1024).toFixed(0)} KB total.
 */
export const STUDIO_FONT_FACE_CSS = \`
${rules}
\`;
`;

fs.writeFileSync(CSS_OUT, header);
console.log("\n" + faces.length + " faces, " + (bytes / 1024).toFixed(0) + " KB -> public/fonts");
console.log("wrote " + path.relative(process.cwd(), CSS_OUT));
